### ISSUE TITLE
Memory Exceeds

### ISSUE THREAD

**Issue by bhardwajjEE** [koyuawsmbrtn/e43#2]
Memory Quota exceeds on deploying to heroku . Any way to solve this ...

**Comment by Soheybot4444** [comment]
> Memory Quota exceeds on deploying to heroku . Any way to solve this ...
I deploy :
https://github.com/bhardwajjEE/Everything-Downloader-Bot
but not work so i deleted repo, please fix that if possible

**Comment by Soheybot4444** [comment]
> Memory Quota exceeds on deploying to heroku . Any way to solve this ...

@youtubecatcherbot also is a clone of e43 but working properly

**Comment by bhardwajjEE** [comment]
> > Memory Quota exceeds on deploying to heroku . Any way to solve this ...
> 
> @youtubecatcherbot also is a clone of e43 but working properly

Maybe it is deployed on Paid tier or Vps ....
